# Generated by Django 5.1.3 on 2024-11-13 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('surname', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('patronymic', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(default='', max_length=30, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
