# Generated by Django 5.1.3 on 2024-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0002_alter_reg_options_alter_reg_managers_reg_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
