# Generated by Django 5.1.3 on 2024-11-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0003_alter_reg_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='surname',
        ),
    ]
