# Generated by Django 5.1.3 on 2024-11-14 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0005_reg_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='username',
        ),
        migrations.AlterField(
            model_name='reg',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=40, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
