# Generated by Django 5.1.3 on 2024-11-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0007_reg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='reg',
            name='username',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
