# Generated by Django 5.1.3 on 2024-12-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0009_alter_reg_managers_alter_reg_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='username',
        ),
    ]
